### ISSUE TITLE
Kitchensink development server crashes due to "Browserslist: caniuse-lite is outdated"

### ISSUE THREAD

**Issue by apriljgranzow** [looker-open-source/extension-examples#92]
# Output from `yarn develop`
```bash
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
/Users/granzow/Downloads/extension-examples/node_modules/react-hot-loader/node_modules/source-map/lib/read-wasm.js:8
      throw new Error("You must provide the URL of lib/mappings.wasm by calling " +
            ^

Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
    at readWasm (/Users/granzow/Downloads/extension-examples/node_modules/react-hot-loader/node_modules/source-map/lib/read-wasm.js:8:13)
    at wasm (/Users/granzow/Downloads/extension-examples/node_modules/react-hot-loader/node_modules/source-map/lib/wasm.js:25:16)
    at /Users/granzow/Downloads/extension-examples/node_modules/react-hot-loader/node_modules/source-map/lib/source-map-consumer.js:264:14

Node.js v19.8.1
error Command failed with exit code 1.
```
## I tried doing what it asked me to do and I got a different error:
```bash
granzow-macbookpro:kitchensink granzow$ npx browserslist@latest --update-db
Need to install the following packages:
  browserslist@4.21.5
Ok to proceed? (y) y

/Users/granzow/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:54
  throw new BrowserslistUpdateError(
  ^
Error [BrowserslistUpdateError]: No lockfile found. Run "npm install", "yarn install" or "pnpm install"
    at detectLockfile (/Users/granzow/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:54:9)
    at updateDB (/Users/granzow/.npm/_npx/072487b38308305a/node_modules/update-browserslist-db/index.js:266:14)
    at Object.<anonymous> (/Users/granzow/.npm/_npx/072487b38308305a/node_modules/browserslist/cli.js:42:3)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  browserslist: true
}

Node.js v19.8.1
```
# My investigation
I noticed that I do not have the same problem with the Hello World Typescript example
So I ran `npm ls browserslist` on both projects:
## Kitchensink
```bash
granzow-macbookpro:kitchensink granzow$ npm ls browserslist
extension-examples@0.8.1 /Users/granzow/Downloads/extension-examples
└─┬ extension-kitchensink@0.11.0 -> ./react/typescript/kitchensink
  ├─┬ @babel/core@7.17.5
  │ └─┬ @babel/helper-compilation-targets@7.16.7
  │   └── browserslist@4.19.3 deduped
  ├─┬ @babel/preset-env@7.16.11
  │ └─┬ core-js-compat@3.21.1
  │   └── browserslist@4.19.3 deduped
  └─┬ webpack@5.69.1
    └── browserslist@4.19.3
```
## Hello World
```bash
granzow-macbookpro:auth-test granzow$ npm ls browserslist
auth-test@0.0.1 /Users/granzow/looker-extension-auth-test/auth-test
├─┬ @babel/core@7.21.8
│ └─┬ @babel/helper-compilation-targets@7.21.5
│   └── browserslist@4.21.5 deduped
├─┬ @babel/preset-env@7.21.5
│ └─┬ core-js-compat@3.30.2
│   └── browserslist@4.21.5 deduped
└─┬ webpack@5.83.0
  └─┬ browserslist@4.21.5
    └─┬ update-browserslist-db@1.0.11
      └── browserslist@4.21.5 deduped
```
I tried upgrading the packages in Kitchensink to match those in Hello World but I'm still getting the same crashing problem.

**Comment by bryans99** [comment]
Please try again with the latest examples. The packages have all been updated and we've switched to npm workspaces rather than yarn. Feel free to create a new issue if you still encounter problems.
